# action.yml
name: 'Jinja2 Templating'
description: 'Flexible Code Templating on your workflows by Jinja2'
branding:
  icon: 'copy'
  color: 'black'
inputs:
  data:  # id of input
    description: 'key value data'
    required: false
    default: 'None'
  datafile:
    description: 'key value file'
    required: false
    default: 'None'
  path:
    description: 'path to target render'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.data }}
    - ${{ inputs.datafile}}
    - ${{ inputs.path }}
