name: Main CI/CD Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: '[run] simple'
        uses: ./
        with:
          data: repo_name=${{ github.event.repository.name }}
          path: tests/test_template_single.py
      - name: '[test] simple'
        run: cat tests/test_template_single.py
      - name: Checkout
        uses: actions/checkout@v2
      - name: '[run] simple'
        uses: ./
        with:
          datafile: tests/template_data.json
          path: tests/multi/*
      - name: '[test] simple'
        run: cat tests/test_template_multi.py
