name: Main CI/CD Pipeline
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: '[run] simple'
        uses: ./
        with:
          data: user=DE
          datafile: tests/template_data.json
          path: tests/test_template.py
      - name: '[test] simple'
        run: cat tests/test_template.py
